### ISSUE TITLE
Submit a package to the typst/packages repository

### ISSUE THREAD

**Issue by Andrew15-5** [peng1999/typst-pyrunner#1]
There is already a "JavaScript [plugin](https://typst.app/docs/reference/foundations/plugin/)" package published in the https://github.com/typst/packages/tree/main/packages/preview/jogs/0.2.0. Have you considered publishing your "Python plugin" package too? I think it would be really great if 2 of the most widely used programming languages can be easily accessed in Typst. I personally prefer Python to JavaScript, so it would be great if the package will be added to the https://github.com/typst/packages in the future.

**Comment by peng1999** [comment]
Thanks for the feedback!

Due to its known limitations, I didn't submit this package to the registry. I believe that aside from demonstrating the power of wasm plugins, it will not serve any practical purpose. But I'm happy to submit it if you want to use this package in you documents.

Can you provide more details about the scenario that you will use this package? Maybe I can improve the interface according to your scenario before submitting it.

**Comment by Andrew15-5** [comment]
> Due to its known limitations

The ones from the README? Well...
- You still can import your own local files into the main Python one, right?
- does `random` module doesn't work at all or it works with a constant seed? Does it even included?
- which Python version is it? It should be at least 3.10.

The limitations are pretty much the same as with JS, aren't they? Then they don't really matter.

The main point is that the standard CPython is much easier, more flexible and sophisticated than Typst. And a lot of people would rather make some kind of script in Python, than in Typst. So at least adding the package as it is would be quite nice rather than not having it in the registry at all, you know what I mean?

> Can you provide more details about the scenario that you will use this package?

I didn't look into it that much. Some similar API to the `jogs` is probably desirable. I need to think first before I can give any personal preferences.

> Maybe I can improve the interface according to your scenario before submitting it.

You certainly can, but you also can submit it ASAP as the first version and then improve in the next version, if it's not too much of a hustle.

**Comment by peng1999** [comment]
Close since typst/packages#270 has been merged.
